### ISSUE TITLE
Not able to create user in 1.4.1 version

### ISSUE THREAD

**Issue by luchees** [featurehub-io/featurehub#494]
**Describe the bug**
After upgrading party server to 1.4.1 I'm not able to create users anymore in the admin console.

I only get an error in js dev-console. no error message in the admin console.

I've tried 1.4.0 and this one is able to create a user

 Which area does this issue belong to?
* [x] FeatureHub Admin Web app

**To Reproduce**
When clicking Create after filling in user information nothing happens.
```
Error in js console
Uncaught Error: NoSuchMethodError: h.d is null
```

**Expected behavior**
user should be created succesfully

**Comment by rvowles** [comment]
Hey, I will take a look now.
